const menu = [ 
    {
        id:1,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:2,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:3,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:4,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:5,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:6,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:7,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:8,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:9,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:10,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:11,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:12,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:13,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:14,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
    {
        id:15,
        img:"",
        images:["","","","",""],
        title:"",
        price:""  
    },
]
export default menu;